import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#39383f",
        "on-primary-container": "#6b4c00",
        "on-secondary": "#690002",
        "secondary-fixed": "#ffdad5",
        "surface-dim": "#131319",
        "primary-fixed-dim": "#ffba20",
        primary: "#ffdca1",
        "on-surface": "#e4e1ea",
        "inverse-surface": "#e4e1ea",
        "tertiary-container": "#c5bdff",
        "surface-container-lowest": "#0d0e13",
        "surface-container-high": "#292930",
        "surface-variant": "#34343b",
        tertiary: "#e2dcff",
        "tertiary-fixed": "#e4dfff",
        "surface-tint": "#ffba20",
        "on-tertiary-container": "#4b2ed5",
        "surface-container": "#1f1f25",
        "primary-fixed": "#ffdea8",
        "on-surface-variant": "#d5c4ab",
        "on-primary-fixed": "#271900",
        "inverse-on-surface": "#303036",
        "on-background": "#e4e1ea",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#930003",
        "on-secondary-fixed": "#410001",
        "on-tertiary-fixed-variant": "#3f1dcb",
        "error-container": "#93000a",
        outline: "#9e8f78",
        background: "#131319",
        "on-secondary-container": "#ffbdb4",
        secondary: "#ffb4a9",
        "surface-container-low": "#1b1b21",
        "primary-container": "#ffb800",
        "outline-variant": "#514532",
        "on-tertiary": "#2a009f",
        "on-primary": "#412d00",
        error: "#ffb4ab",
        "secondary-container": "#b30005",
        "surface-container-highest": "#34343b",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#5e4200",
        "secondary-fixed-dim": "#ffb4a9",
        "on-tertiary-fixed": "#170065",
        "inverse-primary": "#7c5800",
        surface: "#131319",
        "tertiary-fixed-dim": "#c7bfff",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        headline: ["var(--font-inter)", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        float: "float 6s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
